### ISSUE TITLE
Consider scoping contacts resolution to the current user.

### ISSUE THREAD

**Issue by miguelperez** [ericsuescun/contacts#1]
https://github.com/ericsuescun/contacts/blob/21da04b98d6283022f1c1691b9561ad80b93ca5f/app/controllers/contacts_controller.rb#L7

```ruby
@contacts = current_user.contacts.paginate(page: params[:page], per_page: 2) 
```

**Comment by ericsuescun** [comment]
Contact and Import controllers now rely on current_user in order to constrain other users attempts to make operations.
