### ISSUE TITLE
Possible security risk, since any login user could potentially delete any contact

### ISSUE THREAD

**Issue by miguelperez** [ericsuescun/contacts#2]
https://github.com/ericsuescun/contacts/blob/21da04b98d6283022f1c1691b9561ad80b93ca5f/app/controllers/contacts_controller.rb#L25

```ruby
def update
    contact = current_user.contacts.find(params[:id])
    contact.update(contact_params)
    redirect_to contact_path
  end
```

**Comment by ericsuescun** [comment]
Contact and Import controllers rely on current_user to constrain. Individual actions also.
